[flow]
method = "font2svg"
gensvg = true
extsvg = true
gentkz = true

[font_spec]
folder = "../Fonts/"
name   = "texgyreadventor-regular.otf"
alias  = 'texgyre'

[svg_dir]
folder = "SVGs"
sub_1  = "."
sub_2  = "_moreSVGs_"
caps   = "caps"
small  = "small"
nums   = "nums"
others = "others"

[tkz_data]
folder = "../data"
caps   = "ctp-%ALIAS%-alpha-caps.data.tex"
small  = "ctp-%ALIAS%-alpha-small.data.tex"
nums   = "ctp-%ALIAS%-arabic.data.tex"
others = "ctp-%ALIAS%-others.data.tex"
digits = 3
# coor_x = "+\\ctpXshift"
# coor_y = "+\\ctpYshift"
