[flow]
gensvg = true
extsvg = true
gentkz = true

[font_spec]
folder = "../../Fonts/"
name   = "texgyreadventor-regular.otf"
alias  = 'texgyre'

[svg_dir]
folder = "SVGs"
sub_1  = "."
sub_2  = "_moreSVGs_"
caps   = "caps"
small  = "small"
nums   = "nums"
others = "others"

[tkz_data]
folder = "../../data"
caps   = "cpas"
small  = "small"
nums   = "nums"
others = "others"
digits = 3
# coor_x = "+\\ctpXshift"
# coor_y = "+\\ctpYshift"
